### ISSUE TITLE
Some thoughts w.r.t usability (DX)

### ISSUE THREAD

**Issue by dpc** [crywolf/mkchlog#16]
I'm looking at this project through the DX lenses.

Making a valid commit is going to be an extra barrier for
developers, so it's important to smooth out the experience.

#### Commit templates (recommended and maybe auto-generated)

What would help is setting git `commit.template` so
the developer's commit is pre-filled with something
they can edit (including informative comments),
so they have everything they need upfront.

See https://news.ycombinator.com/item?id=29912343 and the discussion there for more useful info.

It can be crafted and maintained manually, but if it could be done automatically would be a nice touch.

Ideally `mkchlog` should be able to generate such a commit template
from the project settings.

Eg. a `mkchlog --commit-template` should output:

```
# Valid changelog sections:
# 
# * features
# * security
#
# Possibly some other things... 
```

etc.

#### Changelog data format

Looking at the [examples of commits](https://github.com/crywolf/mkchlog/tree/be416a0e07decf478cf92c1f14888a90feba617d#commits) 
I have the following comments:

The right-side drift seems already annoying. The extra indentation will making writing (and reading) the message
inconvenient. The whole thing also feels a bit mechanic and yamlish. It might make it easier for the tool to parse, but at the DX expense.

`inherit: all` is very vague.

Would be nice thing if the whole thing was otherwise agnostic, so e.g. one can use it
while retaining ability to use and enforce conventional commits. I think it's already the case, but just pointing it out - it's good if changelog info can blend in between all other stuff people might want to use.

All in all I would suggest turning current:

```
Add ability to skip commits

This allows commits to be skipped by typing changelog: skip
at the end of the commit. This is mainly useful for typo
fixes or other things irrelevant to the user of a project.

changelog:
    inherit: all
    section: features
```

into:

```
Add ability to skip commits

Changelog
===

This allows commits to be skipped by typing changelog: skip
at the end of the commit. This is mainly useful for typo
fixes or other things irrelevant to the user of a project.

section: features
```

What's happening here (contrasted with the current version):

A new section is used to place the changelog information, which is easier
to work with for the developer. Originally I wanted to use `### Changelog` like in Markdown, but I realized that git treats anything starting with `#` as comments, so something else is needed. Can be `====` under ([so it's still valid markdown](https://www.markdownguide.org/basic-syntax/#alternate-syntax)), or could be `Changelog:` header. Possibly parser could support and auto-detect multiple, so people can pick according to their existing preferences.

The important part is avoiding the extra indenation.

The fact that title should be inherited can be just inferred. As long
as "change-log section" is filled and parses, it's known that the developer had to pay attention to it so missing lack of title / other fields is probably not an accident.

Any text in the changelog section that is not prefixed with `somekey: ...` should
become a changelog body. This makes re-using the body for changelog easy and avoids magic `inherit`-like properties.

If the developer does not want to use a changelog body they would write:

```
Add ability to skip commits


This allows commits to be skipped by typing changelog: skip
at the end of the commit. This is mainly useful for typo
fixes or other things irrelevant to the user of a project.

Changelog:

section: features
```

Writing a different commit message and changelog message is also natural.

```
Add ability to skip commits


This allows commits to be skipped by typing changelog: skip
at the end of the commit. This is mainly useful for typo
fixes or other things irrelevant to the user of a project.

Changelog:

You will skip commits and be happy.

section: features
```

The existing example:

```
Fix grammar mistakes

We found 42 grammar mistakes that are fixed in this commit.

changelog: skip
```

could become:

```
Fix grammar mistakes

We found 42 grammar mistakes that are fixed in this commit.

Changelog: skip
```

or 

```
Fix grammar mistakes

We found 42 grammar mistakes that are fixed in this commit.

Changelog:

skip: true
```

or something similar. Or maybe just empty `Changelog:` section altogether is good enough.

**Comment by Kixunil** [comment]
The point about right drift does make sense and I was thinking about it. I specifically made sure to not go above one level. However IME those cases are rare and most of the commits so far really needed just the title. I will think about it more. One thing that sucks about changing the format is that there already are old commits in the old format so the parser has to support both anyway.

Regarding generating commit msg, yes, I already thought about it. I'm not sure what would be a reasonable way to do it. Once #14 is implemented auto-filling project could be done based on files changed.

**Comment by crywolf** [comment]
> One thing that sucks about changing the format is that there already are old commits in the old format so the parser has to support both anyway.

While we play with this tool and it is not used in real projects we can always configure it with
`skip-commits-up-to: COMMIT_NUMBER`

**Comment by Kixunil** [comment]
@crywolf we can but still it would be a shame to lose those changes and having to process them manually. We can deprecate the old way though. Also the only way to actually test it is trying to use it in a real project which I'm trying to do - getting some crates from `rust-bitcoin` to use it and also in all of my projects.

**Comment by crywolf** [comment]
**Regarding the drift (indentation) in changelog part:**
The drift is not necessary, I never required it to be a valid YAML, so I parse it manually since the beginning. It can be also written like this and still work, even with hard wraps (linefeeds):

```
changelog:
section: features
inherit: title
description: Projects in multi-project setting have directory assigned to each of them and files
changed by commit are checked so that commit can change only files that belong to project specified in commit message.
```

**Regarding the commit.template:**
I think better than having statically generated `commit.template` would be to generate hints on the fly while the commit is being made (so that the commit.template is never obsolete and the sections list hint is always up-to-date).

I've already prepared PR with multi-project support, checking if the files changed by the commit belong to the project specified in the `project:` field in the changelog message (described here: https://github.com/crywolf/mkchlog/issues/14#issuecomment-1806877796)
Thus I am validating (by the provided git hook) that the commit complies with the rules.

I want to enhance it so that I am able to also determine beforehand to which project the commit should belong (by inspecting changed files in the staged commit) and programmatically prepare the commit message for the developer with suggested changelog section (by filling the name of the project to `project:` field). Or abort committing in case of error.

**Idea / example:**
static `commit.template`:
```
# Here can be some basic static hints how to use the tool
#
```

Commit message presented to the developer in the editor after typing `git commit`:

```
#changelog:
#    project: mkchlog-action
#    section: X
#    inherit: all
#
# Valid changelog sections:
#
# * security:vuln_fixes	# Fixed vulnerabilities
# * features	# New features
# * bug_fixes	# Fixed bugs
# * breaking	# Breaking changes
# * perf	# Performance improvements
# * dev	# Development
#
# Here can be some basic static hints how to use the tool
#

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# ...and the rest of the default git message... 
```

User is supposed to type the commit message and uncomment and modify the `#changelog:` part at the beginning.

I hope you will like it. Will work on it next week.

**Comment by dpc** [comment]
```
changelog:
section: something
project: foo
```

without indentation still does look a bit confusing as `changelog` doesn't look like any sort of higher-level header, and just another field with an empty value.

> `` would be to generate hints on the fly while the commit is being made

Seems like there's `prepare-commit-msg` git hook, which I wasn't aware of before.

**Comment by dpc** [comment]
>  I, for example, do not understand the difference between inherit: title and title-is-enough: true

Me neither. I mean - I think I did last time I was looking at it, but now I don't and I don't find these informative/intuitive enough to be self-explanatory.

```
* security:vuln_fixes # Fixed vulnerabilities
```

sections using `:` as sub-catagory separator is not a great choice given the `key: value` general structure. Slashes maybe? Or `.`?

```
# Uncomment 'changelog:' part and at least fill in correct 'section'
# from the provided list of valid sections above.
#
# ... Wall of text ...
```

Generally I find it all too long. People are lazy (I am for sure, so I project on other's, but experience tells me I'm not wrong).

I would start with the actual template body uncommented. The commit will be invalid if it's all commented out, so why forcing an extra step.

Section is a wrong word to use. It jumps into the final CHANGELOG having a "section", but IMO "category" is more general and natural to think about. Maybe there's a better word. My point is: the user preparing a commit won't and shouldn't have to think in terms of section in the Changelog file, as they are focused on their change.

Also - if the validation step is informative, there's less need to be verbose.

I wish Changelog was a shorter word. :D . I'm going to try `Chlog` here to keep it short:

```

# Changelog entry custom title, `skip', or `inherit'
Chlog: 

# (optional) Additional multi-line changelog description.

Chlog-Category:
Chlog-Project:

# Valid Changelog Categories (`Chlog-Category'):
#
# * security/vuln_fixes  Fixed vulnerabilities
# * features             New features
# * bug_fixes            Fixed bugs
# * breaking             Breaking changes
# * perf                 Performance improvements
# * dev                  Development
#
# Valid Changelog Projects (`Chlog-Project`):
#
# * lib
# * bin
#
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# ...and the rest of the default git message... 
```

Kind of thing. Mostly just brainstorming.

**Comment by crywolf** [comment]
Good points.

My opinion:
* I agree with uncommenting
* Dot . better than slash /
* Chlog sounds horrible :))

Part with
```
# Valid Changelog Projects (`Chlog-Project`):
#
# * lib
# * bin
```
is not necessary because project should be determined and prefilled automatically, based on files changed. If it fails to determine, it will abort because it means that the user wants to commit changes in more projects at once, or the yaml template is not correctly configured.

**Comment by dpc** [comment]
> Chlog sounds horrible

Agreed. Maybe not worthwhile trying to shorten `Changelog-Foo`. 

> If it fails to determine, it will abort because it means that the user wants to commit changes in more projects at once, or the yaml template is not correctly configured.

This seems overly restrictive, and assumes level of hygiene that many project might not want to deal with. IMO, it would be better to detect, pre-populate and let users decide.

**Comment by Kixunil** [comment]
So first of all, I find the part about valid changelog sections brilliant!

When picking `:` separator I had rusts `::` in mind but simpler but yes, it's weird. I liked slashes more than dots but I'm fine with dots if you prefer those.

I think indentation should be enforced - at least one space. We could make it a convention to use two spaces to minimize right drift while keeping it readable, maybe one is fine too.

Side note: If it's parsed manually anyway and not using `serde_yaml`, we could get spans and report errors with `codespan_reporting`.

`inherit: title` means to copy the first line from the commit as the title. One could still add a custom description:

```
Fix crashes on big input

The recursion was removed as it was causing stack overflows.

changelog:
  section: bug
  inherit: title
  description: The application was crashing when the input contained more than about 1000 items, this is now fixed.
```

Would produce:

```markdown
# Fix crashes on big input

The application was crashing when the input contained more than about 1000 items, this is now fixed.
```

`title-is-enough: true` means "yes, I really mean to not write description, I didn't forget".

> Section is a wrong word to use.

Good point, although it could be a bit confusing to the maintainer that category and section are the same thing. Maybe we could just allow both? It's still useful for projects that already started experimenting with mkchlog.

> fails to determine, it will abort because it means that the user wants to commit changes in more projects at once

I think we shoud allow something like this:

```
Commit title

Commit message

changelog:
  project: foo
    section: bug
    title: How the change affected the project foo
    title-is-enough: true
  project: bar
    skip: true
    # or any other options here
```

This actually happens in practice. In rust-bitcoin we change hashes crate to improve the API and then use the API in `bitcoin`, so both projects are touched. We would generate a changelog entry in hashes describing the API improvement and then either skip `bitcoin` if the change is internal or if it was something like massive performance improvement maybe we would mention it.

And yes, we need to do it in one commit so that it can be tested right away.

**Comment by dpc** [comment]
> I think indentation should be enforced - at least one space. We could make it a convention to use two spaces to minimize right drift while keeping it readable, maybe one is fine too.

The only existing system like that I can think of is Linux kernel mailing list itself, and I wonder if it's worth to try to look ... similar.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f032c53bea6d2057c14553832d846be2f151cfb2

**Comment by crywolf** [comment]
1/ I do not have strong opinion on slash/dot, but slash resembles dir paths. Dot is commonly used in "objects" to denote "going 1 level deeper". But I am OK with slashes as well.

2/ You both are right and I should allow to change more projects in one commit. Actually, it is the main reason for having monorepos, that you can change app and all the dependencies in one go :)

3/ I do not see problem with indentation, it is pretty common and intuitive. Plus if we want to have more projects in the 'changelog:' part, we need to be able separate them and group the info for each project (as in the Kixunil example). Commit template can have 2 spaces as a default indentation. Then I can treat it as a proper YAML and use `serde_yaml` also here.

4/ Section/Category - I do not want to support both. I thought it was beta version but it seems more like just alpha. It turned out that this phase is just experimenting, ideas are wildly changing and so is the API. It would be great if you could involve more of your colleagues to brainstorm and somehow "finalize" the specs. It would greatly help :)

Overall, thanks both for good ideas!

**Comment by Kixunil** [comment]
@dpc LKML appears to use something resembling RFC822 for which I also happen to have [a crate](https://docs.rs/rfc822-like). I'm not sure if it's better but I think it would be usable.

@crywolf 1/ yes, good point
2/ exactly
3/ unfortunately, `serde_yaml` doesn't support spans. :( So the tradeoff is have so simpler code vs easier to understand errors. I would prefer the latter but I can totally understand the desire to get something working out quickly.
4/ I though so as well. One thing that's annoying is we can't have feedback if we don't start using it and we will have hard time changing it if we have users.

**Comment by crywolf** [comment]
Hi guys, we need to decide how the changelog section in commits will look like. Especially when using multiple projects. I do not know how we could implement it without using yaml format, to be honest. In yaml i might look like this

One project in the commit:

```
changelog:
  project: foo
  section: features
  title: How the change affected the project foo
  title-is-enough: true
```

Two projects in one commit (**this should be pretty rare**):

```
changelog:
  project:
    name: foo
    section: features
    title: How the change affected the project foo
    title-is-enough: true
  project: 
    name: bar
    skip: true
```
Version with 1 project is pretty straightforward. Version with 2 projects might look more difficult for unexperienced user, but it has to be valid yaml and actually he does not need to write it down himself. The editor will display commit template with prepared changelog part based on changed files:

```
changelog:
  project:
    name: foo
    section:
    inherit: all
  project:
    name: bar
    section:
    inherit: all
#
# Valid changelog sections:
#
# * security.vuln_fixes  Fixed vulnerabilities
# * features             New features
# * bug_fixes            Fixed bugs
# * breaking             Breaking changes
# * perf                 Performance improvements
# * dev                  Development
```
This should be enough. If the user is not interested in project `bar`, he just can write `skip: true` in that project part or simply comment out or delete the whole `bar` project. **To change more than one project in one commit should be rare anyway.**

Let me know if you have better idea how to do that so I can implement it.

**Comment by Kixunil** [comment]
> To change more than one project in one commit should be rare anyway.

In our experience in Rust-bitcoin it's not really that rare to change e.g. hashes API and simultaneously change each place that uses that API. It's not particularly common but I wouldn't say it's rare either.

I think that accepting both formats is fine. Also as you note, skip is not actually needed if you can delete the part you don't want, so maybe I just wouldn't implement it there.

**Comment by Kixunil** [comment]
`only-title: true`?

**Comment by dpc** [comment]
What is it skipping again? :D

**Comment by dpc** [comment]
@crywolf I like everything except `only-title: true`. Feels clunky again. Some ideas: `format: short`, `verbose: false`, `short: true`, etc.

**Comment by crywolf** [comment]
Thank you for your feedback, but `only-title: true` is the only version that signals what will end up in the final changelog (title, i.e. the first line). Everything else just obscures the intent and can mean anything. Plus it can be prefilled and commented out in the commit template and the user does not need to remember some clunky keyword.

**Comment by Kixunil** [comment]
@crywolf I really don't like the implicitness. It'll be very easy to forget overriding the title/description and then technical details will leak to the user.

@dpc I find "only-title" much more descriptive than "short" what is short about it?

**Comment by crywolf** [comment]
@Kixunil  Currently, the commit template presented to the user says by default `inherit: all` which is not clear at all and because user just wants to commit his work he wont be bothered trying to find out what it means. It was the very first point @dpc mentioned here. 

If the implicitness is a problem, than we should have implemented the version @dpc suggested in his first comment and user should explicitly state the changelog content.

There is also no specification what overrides what, so I just simplified it, because I was confused all the time. Does it mean that I should write both `inherit: title` and `only-title: true`? Why/why not? `inherit: all` together with `only-title: true` is OK or not?

The biggest problem is when the commit is aborted and I lost the message. Then I just mostly used `skip` or `inherit: all`. So my solution is based on my experience.

Because I have to specify `section:` I do not know how I could just forget to think about what I am doing when committing and leak some unimportant stuff. Plus there is that static `commit_template.txt` that can include some simple hints...

**Comment by dpc** [comment]
>  "short" what is short about it?

My thinking was that the commit either generates a long-form entry in the Changelog (title + description), or a short-form (one liner, just the title).

> The biggest problem is when the commit is aborted and I lost the message. Then I just mostly used skip or inherit: all. So my solution is based on my experience.

I'm not sure if understand this flow here. Do you mean that you have to redo commit message and forget to redo the changes to the changelog settings?

BTW I have a neat git alias:

```
reci = "!f() { git commit --edit -F <(cat "$(git rev-parse --git-path COMMIT_EDITMSG)" | grep -v -E '^#.*') "$@"; }; f"
```

which is like `commit` (which I alias as `ci`) but brings back a previous commit message. Happens to me very often as I use gpg on yubikey to sign commits.


Anyway - from the usability perspective, while I'm picky about the words etc. preventing user from forgetting to take care of a changelog seems more important than having them to understand everything upfront. If they do things wrong reviewers will hopefully point it out. And if commit template gives them basic reference and info, then it should be convenient enough to figure it out without hating the tool.

**Comment by crywolf** [comment]
> Oh, I had always and since forever been writing commit messages in my usual text editor.

I 'd been always using just `git commit -m "..."` and only rarely the default editor in shell, which was that one from Midnight Commander long ago and currently is Nano. So I've never learned how to properly use it (and I do not like it, tbh).

Now I usually write it down in Sublime Text and paste it there.

**Comment by crywolf** [comment]
Everything (including https://github.com/crywolf/mkchlog/issues/16#issuecomment-1832331371) is ready to be merged. I believe that I made everything backwards compatible, `inherit:` is deprecated and has no meaning and `only-title: true` is alias to `title-is-enough: true` which is (formally) deprecated.

I believe that all required features are implemented.

**Comment by crywolf** [comment]
@Kixunil reminder, that multi-projects #21 is ready to be merged and used
